bash rice

diff --git a/dot_bashrc b/dot_bashrc
--- a/dot_bashrc
+++ b/dot_bashrc
@@ -1,129 +1,281 @@
-# ~/.bashrc: executed by bash(1) for non-login shells.
-# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
-# for examples
-
-export EDITOR="rider --wait"
+#!/bin/bash
+# ~/.bashrc - Main bash configuration
 
 # If not running interactively, don't do anything
-case $- in
-    *i*) ;;
-      *) return;;
-esac
+[[ $- != *i* ]] && return
 
-# don't put duplicate lines or lines starting with space in the history.
-# See bash(1) for more options
-HISTCONTROL=ignoreboth
-
-# append to the history file, don't overwrite it
-shopt -s histappend
-
-# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
-HISTSIZE=1000
-HISTFILESIZE=2000
-
-# check the window size after each command and, if necessary,
-# update the values of LINES and COLUMNS.
-shopt -s checkwinsize
-
-# If set, the pattern "**" used in a pathname expansion context will
-# match all files and zero or more directories and subdirectories.
-#shopt -s globstar
-
-# make less more friendly for non-text input files, see lesspipe(1)
-[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"
-
-# set variable identifying the chroot you work in (used in the prompt below)
-if [ -z "${debian_chroot:-}" ] && [ -r /etc/debian_chroot ]; then
-    debian_chroot=$(cat /etc/debian_chroot)
+# Source global definitions
+if [ -f /etc/bashrc ]; then
+    . /etc/bashrc
 fi
 
-# set a fancy prompt (non-color, unless we know we "want" color)
-case "$TERM" in
-    xterm-color|*-256color) color_prompt=yes;;
-esac
+# =============================================================================
+# HISTORY SETTINGS
+# =============================================================================
+HISTSIZE=10000                    # Commands in memory
+HISTFILESIZE=20000               # Commands in history file
+HISTCONTROL=ignoreboth:erasedups # Ignore duplicates and lines starting with space
+HISTIGNORE="ls:ll:la:cd:pwd:exit:date:history:clear:bg:fg:jobs"
+HISTTIMEFORMAT="%Y-%m-%d %H:%M:%S "
+shopt -s histappend              # Append to history file, don't overwrite
+shopt -s cmdhist                 # Save multi-line commands as one command
 
-# uncomment for a colored prompt, if the terminal has the capability; turned
-# off by default to not distract the user: the focus in a terminal window
-# should be on the output of commands, not on the prompt
-#force_color_prompt=yes
+# =============================================================================
+# SHELL OPTIONS
+# =============================================================================
+shopt -s checkwinsize            # Check window size after each command
+shopt -s expand_aliases          # Expand aliases
+shopt -s cdspell                 # Correct minor spelling errors in cd
+shopt -s dirspell                # Correct minor spelling errors in directory names
+shopt -s nocaseglob             # Case-insensitive globbing
+shopt -s autocd                 # Change to named directory
+shopt -s globstar               # ** recursive glob
 
-if [ -n "$force_color_prompt" ]; then
-    if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
-	# We have color support; assume it's compliant with Ecma-48
-	# (ISO/IEC-6429). (Lack of such support is extremely rare, and such
-	# a case would tend to support setf rather than setaf.)
-	color_prompt=yes
+# Set vi mode (comment out if you prefer emacs mode)
+set -o vi
+
+# =============================================================================
+# ENVIRONMENT VARIABLES
+# =============================================================================
+export EDITOR="rider --wait"             # Change to vim, emacs, etc. as preferred
+export VISUAL="$EDITOR"
+export PAGER="less"
+export BROWSER="firefox"         # Change as needed
+export TERM="xterm-256color"
+
+# Language and locale
+export LANG="en_US.UTF-8"
+export LC_ALL="en_US.UTF-8"
+
+# Less options
+export LESS="-R -M -i -j5"      # Raw colors, verbose, ignore case, jump 5 lines
+export LESSHISTFILE="/dev/null" # Don't save less history
+
+# Colored man pages
+export LESS_TERMCAP_mb=$'\e[1;32m'     # Begin blinking
+export LESS_TERMCAP_md=$'\e[1;32m'     # Begin bold
+export LESS_TERMCAP_me=$'\e[0m'        # End mode
+export LESS_TERMCAP_se=$'\e[0m'        # End standout-mode
+export LESS_TERMCAP_so=$'\e[01;33m'    # Begin standout-mode
+export LESS_TERMCAP_ue=$'\e[0m'        # End underline
+export LESS_TERMCAP_us=$'\e[1;4;31m'   # Begin underline
+
+# =============================================================================
+# PATH CONFIGURATION
+# =============================================================================
+# Add common directories to PATH if they exist
+for dir in "$HOME/bin" "$HOME/.local/bin" "$HOME/.cargo/bin" "$HOME/go/bin"; do
+    if [[ -d "$dir" && ":$PATH:" != *":$dir:"* ]]; then
+        PATH="$dir:$PATH"
+    fi
+done
+
+# =============================================================================
+# PROMPT CONFIGURATION
+# =============================================================================
+# Color definitions
+RED='\[\033[0;31m\]'
+GREEN='\[\033[0;32m\]'
+YELLOW='\[\033[0;33m\]'
+BLUE='\[\033[0;34m\]'
+PURPLE='\[\033[0;35m\]'
+CYAN='\[\033[0;36m\]'
+WHITE='\[\033[0;37m\]'
+BOLD='\[\033[1m\]'
+RESET='\[\033[0m\]'
+
+# Color definitions for echo (without \[ \] brackets)
+ECHO_RED='\033[0;31m'
+ECHO_GREEN='\033[0;32m'
+ECHO_YELLOW='\033[0;33m'
+ECHO_BLUE='\033[0;34m'
+ECHO_PURPLE='\033[0;35m'
+ECHO_CYAN='\033[0;36m'
+ECHO_WHITE='\033[0;37m'
+ECHO_BOLD='\033[1m'
+ECHO_RESET='\033[0m'
+
+# Git prompt function
+git_prompt() {
+    local git_status git_branch
+    git_branch=$(git symbolic-ref --short HEAD 2>/dev/null)
+    if [[ -n "$git_branch" ]]; then
+        git_status=$(git status --porcelain 2>/dev/null)
+        if [[ -n "$git_status" ]]; then
+            echo " (${git_branch}*)"
+        else
+            echo " (${git_branch})"
+        fi
+    fi
+}
+
+# Set prompt
+if [[ $EUID -eq 0 ]]; then
+    # Root prompt (red)
+    PS1="${RED}${BOLD}${BLUE}\w${YELLOW}\$(git_prompt)${RESET}${RED}# ${RESET}"
+else
+    # Regular user prompt (green)
+    PS1="${GREEN}${BOLD}${BLUE}\w${YELLOW}\$(git_prompt)${RESET}${GREEN}\$ ${RESET}"
+fi
+
+# =============================================================================
+# ALIASES
+# =============================================================================
+# Basic commands
+alias ls='lsd -lha --date "+%d-%m-%Y %H:%M:%S" --blocks date,size,name --group-dirs first'
+alias ll='ls -alF'
+alias la='ls -A'
+alias l='ls -CF'
+alias grep='grep --color=auto'
+alias fgrep='fgrep --color=auto'
+alias egrep='egrep --color=auto'
+
+# Safety nets
+alias rm='rm -i'
+alias cp='cp -i'
+alias mv='mv -i'
+alias ln='ln -i'
+
+# Navigation
+alias ..='cd ..'
+alias ...='cd ../..'
+alias ....='cd ../../..'
+alias .....='cd ../../../..'
+alias ~='cd ~'
+alias -- -='cd -'
+
+# Shortcuts
+alias h='history'
+alias j='jobs -l'
+alias c='clear'
+alias x='exit'
+alias q='exit'
+
+# System information
+alias df='df -h'
+alias du='du -h'
+alias free='free -h'
+alias ps='ps auxf'
+alias psg='ps aux | grep -v grep | grep -i -e VSZ -e'
+alias top='htop'
+
+# Network
+alias ping='ping -c 5'
+alias ports='netstat -tulanp'
+alias myip='curl -s ifconfig.me'
+
+# Date and time
+alias now='date +"%T"'
+alias nowdate='date +"%d-%m-%Y"'
+
+# Archives
+alias mktar='tar -cvf'
+alias mkbz2='tar -cvjf'
+alias mkgz='tar -cvzf'
+alias untar='tar -xvf'
+alias unbz2='tar -xvjf'
+alias ungz='tar -xvzf'
+
+# =============================================================================
+# FUNCTIONS
+# =============================================================================
+# Create directory and cd into it
+mkcd() {
+    mkdir -p "$1" && cd "$1"
+}
+
+# Extract various archive formats
+extract() {
+    if [ -f "$1" ]; then
+        case $1 in
+            *.tar.bz2)   tar xjf "$1"     ;;
+            *.tar.gz)    tar xzf "$1"     ;;
+            *.bz2)       bunzip2 "$1"     ;;
+            *.rar)       unrar x "$1"     ;;
+            *.gz)        gunzip "$1"      ;;
+            *.tar)       tar xf "$1"      ;;
+            *.tbz2)      tar xjf "$1"     ;;
+            *.tgz)       tar xzf "$1"     ;;
+            *.zip)       unzip "$1"       ;;
+            *.Z)         uncompress "$1"  ;;
+            *.7z)        7z x "$1"        ;;
+            *)           echo "'$1' cannot be extracted via extract()" ;;
+        esac
     else
-	color_prompt=
+        echo "'$1' is not a valid file"
+    fi
+}
+
+# Find file by name
+ff() {
+    find . -type f -name "*$1*" 2>/dev/null
+}
+
+# Find directory by name
+fd() {
+    find . -type d -name "*$1*" 2>/dev/null
+}
+
+# Show PATH in readable format
+path() {
+    echo "$PATH" | tr ':' '\n' | nl
+}
+
+# Weather function (requires curl)
+weather() {
+    local location="${1:-}"
+    curl -s "wttr.in/${location}?format=3"
+}
+
+trim() {
+    local var="$*"
+    # Remove leading whitespace
+    var="${var#"${var%%[![:space:]]*}"}"
+    # Remove trailing whitespace
+    var="${var%"${var##*[![:space:]]}"}"
+    printf '%s' "$var"
+}
+
+# =============================================================================
+# COMPLETION
+# =============================================================================
+# Enable programmable completion features
+if ! shopt -oq posix; then
+    if [ -f /usr/share/bash-completion/bash_completion ]; then
+        . /usr/share/bash-completion/bash_completion
+    elif [ -f /etc/bash_completion ]; then
+        . /etc/bash_completion
     fi
 fi
 
-if [ "$color_prompt" = yes ]; then
-    PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
-else
-    PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '
-fi
-unset color_prompt force_color_prompt
-
-# If this is an xterm set the title to user@host:dir
-case "$TERM" in
-xterm*|rxvt*)
-    PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]$PS1"
-    ;;
-*)
-    ;;
-esac
-
-# enable color support of ls and also add handy aliases
-if [ -x /usr/bin/dircolors ]; then
-    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
-    alias ls='ls --color=auto'
-    #alias dir='dir --color=auto'
-    #alias vdir='vdir --color=auto'
-
-    alias grep='grep --color=auto'
-    alias fgrep='fgrep --color=auto'
-    alias egrep='egrep --color=auto'
+# =============================================================================
+# ADDITIONAL CONFIGURATIONS
+# =============================================================================
+# Load local bashrc if it exists
+if [ -f ~/.bashrc.local ]; then
+    . ~/.bashrc.local
 fi
 
-# colored GCC warnings and errors
-#export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'
-
-# some more ls aliases
-alias ll='ls -alF'
-alias lsa='ls -A'
-alias l='ls -CF'
-
-# Add an "alert" alias for long running commands.  Use like so:
-#   sleep 10; alert
-alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'
-
-# Alias definitions.
-# You may want to put all your additions into a separate file like
-# ~/.bash_aliases, instead of adding them here directly.
-# See /usr/share/doc/bash-doc/examples in the bash-doc package.
-
-if [ -f ~/.bash_aliases ]; then
-    . ~/.bash_aliases
+# Load work-specific configuration if it exists
+if [ -f ~/.bashrc.work ]; then
+    . ~/.bashrc.work
 fi
 
-alias ls='lsd -lha --date "+%d-%m-%Y %H:%M:%S" --blocks date,size,name --group-dirs first'
-
-# enable programmable completion features (you don't need to enable
-# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
-# sources /etc/bash.bashrc).
-if ! shopt -oq posix; then
-  if [ -f /usr/share/bash-completion/bash_completion ]; then
-    . /usr/share/bash-completion/bash_completion
-  elif [ -f /etc/bash_completion ]; then
-    . /etc/bash_completion
-  fi
+# Welcome message (fixed)
+if [[ -t 1 ]]; then
+    echo -e "${ECHO_BLUE}Today is $(date '+%A, %B %d, %Y')${ECHO_RESET}"
+    
+    # Show system info (trim leading whitespace)
+    if command -v uptime &> /dev/null; then
+        echo -e "${ECHO_YELLOW}$(uptime | sed 's/^ *//')${ECHO_RESET}"
+    fi
 fi
 
+# =============================================================================
+# PATH
+# =============================================================================
 export PATH="/home/jsc/.local/bin:$PATH"
-
 export PATH="$PATH:$HOME/.dotnet/tools"
 export NVM_DIR="$HOME/.nvm"
 [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
 [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
-
